# Generated by Django 4.2.7 on 2023-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('current_location', models.CharField(choices=[('CITY4', 'City 4'), ('CITY5', 'City 5'), ('CITY6', 'City 6'), ('CITY7', 'City 7')], default='CITY4', max_length=20)),
                ('destination', models.CharField(choices=[('CITY1', 'City 1'), ('CITY2', 'City 2'), ('CITY3', 'City 3')], default='CITY1', max_length=20)),
            ],
        ),
    ]
